apiVersion: v1
kind: Service
metadata:
  name: hitcounter
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hitcounter
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
