{{- if not .Values.istio.ingressGateway }}
{{- if not .Values.openshift.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hitcounter
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hitcounter
                port:
                  number: 80
{{- end }}
{{- if .Values.openshift.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hitcounter
spec:
  host: {{ .Values.openshift.route.host }}
  to:
    kind: Service
    name: hitcounter
  port:
    targetPort: http
  tls:
    termination: {{ .Values.openshift.route.tlsTermination }}
{{- end }}
{{- end }}
