apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
      {{- if not .Values.openshift.enabled }}
        {{- if .Values.redis.securityContext.runAsUser }}
        runAsUser: {{ .Values.redis.securityContext.runAsUser }}
        {{- end }}
        {{- if .Values.redis.securityContext.runAsGroup }}
        runAsGroup: {{ .Values.redis.securityContext.runAsGroup }}
        {{- end }}
        {{- if .Values.redis.securityContext.fsGroup }}
        fsGroup: {{ .Values.redis.securityContext.fsGroup }}
        {{- end }}
      {{- end }}             
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.redis.pullSecret }}
          imagePullSecrets:
          - name: {{ .Values.redis.pullSecret }}
          {{- end }}
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["sh","-c","redis-cli ping | grep -q PONG"]
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command: ["sh","-c","redis-cli ping | grep -q PONG"]
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: {{ .Values.redis.requests.cpu }}
              memory: {{ .Values.redis.requests.memory }}
            limits:
              cpu: {{ .Values.redis.limits.cpu }}
              memory: {{ .Values.redis.limits.memory }}            
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
