{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hitcounter
spec:
  to:
    kind: Service
    name: hitcounter
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tlsTermination }}
{{- end }}
