apiVersion: v1
kind: Service
metadata:
  name: hitcounter
  labels:
    app: hitcounter
spec:
  type: ClusterIP
  selector:
    app: hitcounter
  ports:
    - name: http
      port: 80
      targetPort: 8080
