apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hitcounter
spec:
  ingressClassName: traefik
  rules:
    - host: hitcounter.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hitcounter
                port:
                  number: 80
