replicaCount: 2

image:
  repository: ghcr.io/paulovigne/hitcounter
  tag: main
  pullPolicy: Always
  pullSecret: null

serviceAccount:
  create: true
  name: hitcounter-sa
  automount: false

# Ignored if openshift.enabled: true
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

requests:
  cpu: 50m
  memory: 64Mi
limits:
  cpu: 200m
  memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  port: "8080"
  enableRedis: true
  redisHost: redis
  redisPort: "6379"

istio:
  ingressGateway: true

openshift:
  enabled: false
  # Route Ignored if istio.ingressGateway: true
  route:
    host: null
    tlsTermination: edge

# Ignored if openshift.enabled: true or istio.ingressGateway: true
ingress:
  className: traefik
  host: hitcounter.local

redis:
  image: redis:7-alpine
  pullPolicy: Always
  pullSecret: null
  storage: 1Gi
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi  
