replicaCount: 2

image:
  repository: ghcr.io/paulovigne/hit-counter
  tag: main
  pullPolicy: Always

serviceAccount:
  create: true
  name: hitcounter-sa
  automount: false

# Ignored if openshift.enabled: true
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  port: "8080"
  enableRedis: "true"
  redisHost: redis
  redisPort: "6379"

redis:
  image: redis:7-alpine
  storage: 1Gi

openshift:
  enabled: false
  route:
    host: null
    tlsTermination: edge

# Ignored if openshift.enabled: true
ingress:
  className: traefik
  host: hitcounter.local
